Moez/ruberics read me
RobinNagpal/dodao-ui pull request #289
Opened 2024-07-04 17:45 UTC by moezthedev

# Pull Request Template

Before submitting this PR, please make sure you have completed the following checklist. This helps ensure that our codebase remains high quality and that our features work well across all supported devices and themes.

### Code Review
- [x] I have carefully reviewed my code and believe it is final from my side.
- [x] I have ensured there is no hardcoded color in my changes. Colors should be defined in theme files and reused.

### Theme Compatibility
- [x] I have tested the new feature or updates in both light and dark themes.
- [x] I confirm that the visual aspects of the feature are compatible and appealing in both themes.

### Device Compatibility
- [x] I have tested my changes on mobile screen sizes.
- [x] I have tested my changes on tablet screen sizes.
- [x] I have tested my changes on laptop screen sizes.

### Functional Testing
- [x] I have thoroughly tested the functionality of my changes.
- [x] I am confident that my changes do not negatively impact existing features.

### Testing Documentation
Please provide a brief description of the tests you have performed to verify your changes. Include any relevant scenarios or edge cases.

- Example test 1: Tested feature X by uploading the image
- Example test 2: Tested feature X by doing these things.

# Demo Video
Please provide a demo video of your changes. This helps reviewers understand the changes and verify the functionality.

You can record the video using tools like Loom(https://www.loom.com/), Clip by ClickUp(https://clickup.com/features/clips), Sendspark(https://www.sendspark.com/), etc.

Include the link to the video below and make sure the video covers
- [x] Explain the task/bug you are solving
- [x] Show the changes in the UI
- [x] Show the changes in the codebase
- [x] Show the changes you tested to make sure it works
- [x] Show the changes in various screen sizes
- [x] Show the changes in both light and dark themes
Video:https://www.loom.com/share/ad768c9e6a1a4727b6f5d74b835d4b35

2024-07-04 18:36 UTC, MSamiTariq requested changes

2024-07-04 18:36 UTC, MSamiTariq commented on rubrics-ui/src/app/api/ruberics/create-programs/route.ts
> +export async function POST(req: NextRequest, res: NextApiResponse) {
make the type of res consistent with NextResponse

2024-07-04 18:36 UTC, MSamiTariq commented on rubrics-ui/src/app/api/ruberics/create-programs/route.ts
> +  if (req.method === 'POST') {
We don't need to check the request type

2024-07-04 18:36 UTC, MSamiTariq commented on rubrics-ui/src/components/rubricsTable/rubricsTable.tsx
> +import { RubricsPageProps } from '../../types/rubricsTypes/types';
We don't usually specify the path this way, see examples in other files

2024-07-04 18:36 UTC, MSamiTariq commented on rubrics-ui/src/app/api/ruberics/create-programs/route.ts
> +      return NextResponse.json({ status: '200', body: newProgram });
status should be a number, not a string

2024-07-04 18:36 UTC, MSamiTariq commented on rubrics-ui/src/app/api/ruberics/create-programs/route.ts
> +      }
Only name field is mandatory? I think we should handle this case on the front end. If any field is missing, return a 404 error

2024-07-04 18:36 UTC, MSamiTariq commented on rubrics-ui/src/app/api/ruberics/create-programs/route.ts
> +    return NextResponse.json({ status: '405', body: 'Method not allowed' });
I don't think we need this either

2024-07-04 18:36 UTC, MSamiTariq commented on rubrics-ui/src/app/api/ruberics/create-programs/route.ts
> +const prisma = new PrismaClient();
initialize the prisma client in a separate file and then import it, else this will error out with too many prisma clients. See academy-ui for inspiration on how we do this

2024-07-04 18:36 UTC, MSamiTariq commented on rubrics-ui/src/app/api/ruberics/create-rubrics/route.ts
> +const prisma = new PrismaClient();
Same goes here, initialize in a separate file

2024-07-04 18:36 UTC, MSamiTariq commented on rubrics-ui/src/app/api/ruberics/create-rubrics/route.ts
> +    }
This should be handled on the front end

2024-07-04 18:36 UTC, MSamiTariq commented on rubrics-ui/src/app/api/ruberics/create-rubrics/route.ts
> +    }
same goes for this, handle this on front end

2024-07-04 18:36 UTC, MSamiTariq commented on rubrics-ui/src/app/editrubrics/page.tsx
> +import ProgramList from '../../components/programList/programList';
correct the path

2024-07-04 18:36 UTC, MSamiTariq commented on rubrics-ui/src/app/editrubrics/page.tsx
folder name should be 'edit-rubrics'

2024-07-12 18:24 UTC, MSamiTariq requested changes

2024-07-12 18:24 UTC, MSamiTariq commented on rubrics-ui/src/components/programList/programList.tsx
> +      const response = await fetch('/api/ruberics/create-programs', {
endpoint should be called `/create-program` as it creates a single program only

2024-07-12 18:24 UTC, MSamiTariq commented on rubrics-ui/src/components/programList/programList.tsx
> +      router.refresh();
we should look for some way to fetch the programs instead of refreshing the page

2024-07-12 18:24 UTC, MSamiTariq commented on rubrics-ui/src/types/rubricsTypes/types.ts
> +}
maybe rename this interface to something specific to Program

2024-07-12 18:24 UTC, MSamiTariq commented on rubrics-ui/src/components/rubricsTable/rubricsTable.tsx
> +        return 'bg-gray-400';
confirm with Robin if these should be hard coded

2024-07-12 18:24 UTC, MSamiTariq commented on rubrics-ui/src/components/rubricsTable/rubricsTable.tsx
> +                  <button onClick={() => handleDeleteCriteria(criteria)} className="absolute top-0 right-0 bg-red-500 text-white p-0.5 rounded-half">
you can use a trash bin icon for delete, and the delete icon position to may be at the end of the row

2024-07-15 18:42 UTC, RobinNagpal commented on rubrics-ui/prisma/migrations/20240715174819_initial/migration.sql
> +    "programId" TEXT NOT NULL,
We will not have programId in Rubric. You can remove this column for now

2024-07-15 18:42 UTC, RobinNagpal commented on rubrics-ui/prisma/migrations/20240715174819_initial/migration.sql
> +    "programId" TEXT NOT NULL,
We will have a mapping table which we can add in the next PR

2024-07-16 16:24 UTC, merged